-- SCM 실판매 통합 스키마 초안
-- 검토 후 Supabase에 적용합니다. 기존 05. 영업 실적 원본은 변경하지 않습니다.

create table if not exists public."SCM거래처" (
  "거래처코드" text primary key,
  "거래처명" text not null unique,
  "사용여부" boolean not null default true,
  "생성일시" timestamptz not null default now(),
  "수정일시" timestamptz not null default now()
);

insert into public."SCM거래처" ("거래처코드", "거래처명") values
  ('KYOBO', '교보문고'),
  ('YPBOOKS', '영풍문고'),
  ('YES24', '예스24'),
  ('ALADIN', '알라딘')
on conflict ("거래처코드") do update set
  "거래처명" = excluded."거래처명",
  "사용여부" = true,
  "수정일시" = now();

create table if not exists public."SCM제품매핑" (
  "ISBN13" text primary key,
  "제품코드" text references public."제품인덱스" ("제품코드")
    on update cascade on delete set null,
  "SCM상품명" text,
  "출판일자" date,
  "매칭상태" text not null default '미매칭'
    check ("매칭상태" in ('자동매칭', '수동매칭', '미매칭')),
  "매칭근거" text,
  "최초확인일" date,
  "최종확인일" date,
  "생성일시" timestamptz not null default now(),
  "수정일시" timestamptz not null default now(),
  constraint "SCM제품매핑_ISBN13_형식" check ("ISBN13" ~ '^[0-9]{10,13}$')
);

create index if not exists "SCM제품매핑_제품코드_idx"
  on public."SCM제품매핑" ("제품코드");
create index if not exists "SCM제품매핑_매칭상태_idx"
  on public."SCM제품매핑" ("매칭상태");

create table if not exists public."SCM동기화이력" (
  "동기화ID" uuid primary key default gen_random_uuid(),
  "시작일시" timestamptz not null default now(),
  "종료일시" timestamptz,
  "대상시작일" date,
  "대상종료일" date,
  "원천파일명" text,
  "원천파일해시" text,
  "상태" text not null default '진행'
    check ("상태" in ('진행', '성공', '부분성공', '실패', '검증실패')),
  "전체건수" integer not null default 0,
  "신규건수" integer not null default 0,
  "수정건수" integer not null default 0,
  "동일건수" integer not null default 0,
  "오류건수" integer not null default 0,
  "미매칭건수" integer not null default 0,
  "YES24원본파일수" integer not null default 0,
  "YES24구매자스냅샷건수" integer not null default 0,
  "YES24구매자분포건수" integer not null default 0,
  "원천판매수량합계" bigint not null default 0,
  "DB판매수량합계" bigint,
  "오류내용" text,
  "프로그램버전" text,
  "생성일시" timestamptz not null default now()
);

create index if not exists "SCM동기화이력_시작일시_idx"
  on public."SCM동기화이력" ("시작일시" desc);
create index if not exists "SCM동기화이력_상태_idx"
  on public."SCM동기화이력" ("상태");

-- 동기화 전체 검증이 끝날 때까지 운영 원장을 건드리지 않기 위한 내부 적재 영역입니다.
create table if not exists public."SCM동기화스테이징" (
  "동기화ID" uuid not null references public."SCM동기화이력" ("동기화ID") on delete cascade,
  "판매일" date not null,
  "거래처코드" text not null references public."SCM거래처" ("거래처코드"),
  "ISBN13" text not null,
  "제품코드" text,
  "SCM상품명" text,
  "출판일자" date,
  "판매수량" integer not null,
  "원본파일명" text,
  "원본시트" text,
  primary key ("동기화ID", "판매일", "거래처코드", "ISBN13")
);

create index if not exists "SCM동기화스테이징_동기화ID_idx"
  on public."SCM동기화스테이징" ("동기화ID");
create index if not exists "SCM동기화스테이징_거래처코드_idx"
  on public."SCM동기화스테이징" ("거래처코드");

create table if not exists public."SCM동기화거래처결과" (
  "결과ID" bigint generated by default as identity primary key,
  "동기화ID" uuid not null references public."SCM동기화이력" ("동기화ID")
    on delete cascade,
  "거래처코드" text not null references public."SCM거래처" ("거래처코드")
    on update cascade on delete restrict,
  "처리건수" integer not null default 0,
  "판매수량합계" bigint not null default 0,
  "신규건수" integer not null default 0,
  "수정건수" integer not null default 0,
  "동일건수" integer not null default 0,
  "오류건수" integer not null default 0,
  "오류내용" text,
  "생성일시" timestamptz not null default now(),
  constraint "SCM동기화거래처결과_동기화_거래처_uq"
    unique ("동기화ID", "거래처코드")
);

create index if not exists "SCM동기화거래처결과_동기화ID_idx"
  on public."SCM동기화거래처결과" ("동기화ID");
create index if not exists "SCM동기화거래처결과_거래처코드_idx"
  on public."SCM동기화거래처결과" ("거래처코드");

create table if not exists public."SCM일별실판매" (
  "SCM실판매ID" bigint generated by default as identity primary key,
  "판매일" date not null,
  "거래처코드" text not null references public."SCM거래처" ("거래처코드")
    on update cascade on delete restrict,
  "ISBN13" text not null references public."SCM제품매핑" ("ISBN13")
    on update cascade on delete restrict,
  "제품코드" text references public."제품인덱스" ("제품코드")
    on update cascade on delete set null,
  "판매수량" integer not null,
  "판매금액" bigint,
  "원본파일명" text,
  "원본시트" text,
  "동기화ID" uuid references public."SCM동기화이력" ("동기화ID")
    on delete set null,
  "수집일시" timestamptz,
  "생성일시" timestamptz not null default now(),
  "수정일시" timestamptz not null default now(),
  constraint "SCM일별실판매_판매일_거래처_ISBN_uq"
    unique ("판매일", "거래처코드", "ISBN13")
);

create index if not exists "SCM일별실판매_제품_판매일_idx"
  on public."SCM일별실판매" ("제품코드", "판매일");
create index if not exists "SCM일별실판매_거래처_판매일_idx"
  on public."SCM일별실판매" ("거래처코드", "판매일");
create index if not exists "SCM일별실판매_ISBN_판매일_idx"
  on public."SCM일별실판매" ("ISBN13", "판매일");
create index if not exists "SCM일별실판매_판매일_idx"
  on public."SCM일별실판매" ("판매일");
create index if not exists "SCM일별실판매_동기화ID_idx"
  on public."SCM일별실판매" ("동기화ID");

-- YES24 파일은 일자별 단일일 조회 결과이며 성별·연령·지역은 서로 독립된 주변분포입니다.
create table if not exists public."YES24구매자스냅샷" (
  "스냅샷ID" bigint generated by default as identity primary key,
  "기준일" date not null,
  "기간시작일" date not null,
  "기간종료일" date not null,
  "계정구분" text not null check ("계정구분" in ('성인', '아동')),
  "ISBN13" text not null references public."SCM제품매핑" ("ISBN13")
    on update cascade on delete restrict,
  "제품코드" text references public."제품인덱스" ("제품코드")
    on update cascade on delete set null,
  "YES24상품번호" text,
  "상품명" text,
  "총판매수량" integer not null,
  "원본파일명" text not null,
  "원본파일해시" text not null,
  "원본시트" text,
  "동기화ID" uuid references public."SCM동기화이력" ("동기화ID") on delete set null,
  "수집일시" timestamptz not null default now(),
  constraint "YES24구매자스냅샷_기준일_계정_ISBN_uq" unique ("기준일", "계정구분", "ISBN13"),
  constraint "YES24구매자스냅샷_단일일_ck" check ("기준일" = "기간시작일" and "기준일" = "기간종료일")
);

create index if not exists "YES24구매자스냅샷_제품_기준일_idx"
  on public."YES24구매자스냅샷" ("제품코드", "기준일");
create index if not exists "YES24구매자스냅샷_ISBN_기준일_idx"
  on public."YES24구매자스냅샷" ("ISBN13", "기준일");
create index if not exists "YES24구매자스냅샷_동기화ID_idx"
  on public."YES24구매자스냅샷" ("동기화ID");

create table if not exists public."YES24구매자분포" (
  "스냅샷ID" bigint not null references public."YES24구매자스냅샷" ("스냅샷ID") on delete cascade,
  "분포유형" text not null check ("분포유형" in ('성별', '연령', '지역')),
  "구간값" text not null,
  "수량" integer not null,
  "정렬순서" smallint not null,
  primary key ("스냅샷ID", "분포유형", "구간값")
);

create index if not exists "YES24구매자분포_유형_구간_idx"
  on public."YES24구매자분포" ("분포유형", "구간값");

-- 113개 과거 파일과 향후 신규 파일을 같은 방식으로 원자 확정하기 위한 내부 영역입니다.
create table if not exists public."YES24구매자스테이징" (
  "동기화ID" uuid not null references public."SCM동기화이력" ("동기화ID") on delete cascade,
  "기준일" date not null,
  "계정구분" text not null check ("계정구분" in ('성인', '아동')),
  "ISBN13" text not null,
  "YES24상품번호" text,
  "상품명" text,
  "총판매수량" integer not null,
  "성별분포" jsonb not null,
  "연령분포" jsonb not null,
  "지역분포" jsonb not null,
  "원본파일명" text not null,
  "원본파일해시" text not null,
  "원본시트" text,
  primary key ("동기화ID", "기준일", "계정구분", "ISBN13")
);

-- 한 트랜잭션에서 검증된 날짜·거래처 범위만 교체합니다.
-- SECURITY INVOKER로 호출자의 권한과 RLS를 그대로 따릅니다.
create or replace function public."SCM동기화확정"("대상동기화ID" uuid)
returns table ("반영건수" bigint, "판매수량합계" bigint, "YES24스냅샷건수" bigint, "YES24분포건수" bigint)
language plpgsql
security invoker
set search_path = public
set statement_timeout = '300s'
as $$
declare
  staged_count bigint;
  staged_qty bigint;
  yes24_snapshot_count bigint;
  yes24_distribution_count bigint;
begin
  select count(*), coalesce(sum(s."판매수량"), 0)
    into staged_count, staged_qty
  from public."SCM동기화스테이징" s
  where s."동기화ID" = "대상동기화ID";

  if staged_count = 0 then
    raise exception '확정할 SCM 스테이징 데이터가 없습니다.';
  end if;

  insert into public."SCM제품매핑" (
    "ISBN13", "제품코드", "SCM상품명", "출판일자", "매칭상태", "매칭근거", "최초확인일", "최종확인일", "수정일시"
  )
  select
    s."ISBN13",
    max(s."제품코드"),
    max(s."SCM상품명"),
    min(s."출판일자"),
    case when max(s."제품코드") is null then '미매칭' else '자동매칭' end,
    '실판매_통합원장.xlsx',
    min(s."판매일"),
    max(s."판매일"),
    now()
  from public."SCM동기화스테이징" s
  where s."동기화ID" = "대상동기화ID"
  group by s."ISBN13"
  on conflict ("ISBN13") do update set
    "제품코드" = case
      when public."SCM제품매핑"."매칭상태" = '수동매칭' then public."SCM제품매핑"."제품코드"
      else coalesce(excluded."제품코드", public."SCM제품매핑"."제품코드")
    end,
    "SCM상품명" = coalesce(excluded."SCM상품명", public."SCM제품매핑"."SCM상품명"),
    "출판일자" = coalesce(excluded."출판일자", public."SCM제품매핑"."출판일자"),
    "매칭상태" = case
      when public."SCM제품매핑"."매칭상태" = '수동매칭' then '수동매칭'
      when coalesce(excluded."제품코드", public."SCM제품매핑"."제품코드") is null then '미매칭'
      else '자동매칭'
    end,
    "최초확인일" = least(public."SCM제품매핑"."최초확인일", excluded."최초확인일"),
    "최종확인일" = greatest(public."SCM제품매핑"."최종확인일", excluded."최종확인일"),
    "수정일시" = now();

  -- 판매 통합원장에 없더라도 YES24 ISBN은 매핑 원장에 보존합니다.
  insert into public."SCM제품매핑" (
    "ISBN13", "SCM상품명", "매칭상태", "매칭근거", "최초확인일", "최종확인일", "수정일시"
  )
  select y."ISBN13", max(y."상품명"), '미매칭', 'YES24 일별 원본', min(y."기준일"), max(y."기준일"), now()
  from public."YES24구매자스테이징" y
  where y."동기화ID" = "대상동기화ID"
  group by y."ISBN13"
  on conflict ("ISBN13") do update set
    "SCM상품명" = coalesce(public."SCM제품매핑"."SCM상품명", excluded."SCM상품명"),
    "최초확인일" = least(public."SCM제품매핑"."최초확인일", excluded."최초확인일"),
    "최종확인일" = greatest(public."SCM제품매핑"."최종확인일", excluded."최종확인일"),
    "수정일시" = now();

  -- 원장에 있던 행이 다음 수집에서 완전히 사라진 경우까지 맞추기 위해
  -- 스테이징의 전체 날짜 범위와 대상 거래처를 교체합니다.
  delete from public."SCM일별실판매" f
  where f."판매일" between (
      select min(s."판매일") from public."SCM동기화스테이징" s
      where s."동기화ID" = "대상동기화ID"
    ) and (
      select max(s."판매일") from public."SCM동기화스테이징" s
      where s."동기화ID" = "대상동기화ID"
    )
    and f."거래처코드" in (
      select distinct s."거래처코드" from public."SCM동기화스테이징" s
      where s."동기화ID" = "대상동기화ID"
    );

  insert into public."SCM일별실판매" (
    "판매일", "거래처코드", "ISBN13", "제품코드", "판매수량",
    "원본파일명", "원본시트", "동기화ID", "수집일시", "수정일시"
  )
  select
    s."판매일", s."거래처코드", s."ISBN13", m."제품코드", s."판매수량",
    s."원본파일명", s."원본시트", s."동기화ID", now(), now()
  from public."SCM동기화스테이징" s
  join public."SCM제품매핑" m on m."ISBN13" = s."ISBN13"
  where s."동기화ID" = "대상동기화ID";

  -- 실제로 존재하는 YES24 파일 범위만 교체하여 동일 파일 재처리와 원본 행 삭제를 모두 반영합니다.
  delete from public."YES24구매자스냅샷" target
  using (
    select distinct y."기준일", y."계정구분"
    from public."YES24구매자스테이징" y
    where y."동기화ID" = "대상동기화ID"
  ) scope
  where target."기준일" = scope."기준일" and target."계정구분" = scope."계정구분";

  insert into public."YES24구매자스냅샷" (
    "기준일", "기간시작일", "기간종료일", "계정구분", "ISBN13", "제품코드",
    "YES24상품번호", "상품명", "총판매수량", "원본파일명", "원본파일해시",
    "원본시트", "동기화ID", "수집일시"
  )
  select y."기준일", y."기준일", y."기준일", y."계정구분", y."ISBN13", m."제품코드",
    y."YES24상품번호", y."상품명", y."총판매수량", y."원본파일명", y."원본파일해시",
    y."원본시트", y."동기화ID", now()
  from public."YES24구매자스테이징" y
  join public."SCM제품매핑" m on m."ISBN13" = y."ISBN13"
  where y."동기화ID" = "대상동기화ID";

  insert into public."YES24구매자분포" ("스냅샷ID", "분포유형", "구간값", "수량", "정렬순서")
  select snap."스냅샷ID", source."분포유형", value.key, (value.value)::integer,
    case source."분포유형"
      when '성별' then array_position(array['남','녀','미가입'], value.key)
      when '연령' then array_position(array['기타','10대 이하','20대 초','20대 후','30대 초','30대 후','40대 초','40대 후','50대 초','50대 후','60대 이상'], value.key)
      else array_position(array['서울','경기','충청','경상','전라','강원','제주'], value.key)
    end::smallint
  from public."YES24구매자스테이징" y
  join public."YES24구매자스냅샷" snap
    on snap."기준일" = y."기준일" and snap."계정구분" = y."계정구분" and snap."ISBN13" = y."ISBN13"
  cross join lateral (values ('성별', y."성별분포"), ('연령', y."연령분포"), ('지역', y."지역분포")) source("분포유형", payload)
  cross join lateral jsonb_each_text(source.payload) value
  where y."동기화ID" = "대상동기화ID";

  select count(*) into yes24_snapshot_count
  from public."YES24구매자스테이징" y where y."동기화ID" = "대상동기화ID";
  select count(*) into yes24_distribution_count
  from public."YES24구매자분포" d
  join public."YES24구매자스냅샷" s on s."스냅샷ID" = d."스냅샷ID"
  where s."동기화ID" = "대상동기화ID";

  return query select staged_count, staged_qty, yes24_snapshot_count, yes24_distribution_count;
end;
$$;

comment on table public."SCM제품매핑" is
  'SCM ISBN과 기존 제품인덱스 제품코드의 연결표. 별도 제품 마스터가 아님.';
comment on table public."SCM일별실판매" is
  '기존 실판매 통합원장에서 동기화한 제품(ISBN)×거래처×판매일 Grain의 SCM 실판매 원장.';

alter table public."SCM거래처" enable row level security;
alter table public."SCM제품매핑" enable row level security;
alter table public."SCM동기화이력" enable row level security;
alter table public."SCM동기화스테이징" enable row level security;
alter table public."SCM동기화거래처결과" enable row level security;
alter table public."SCM일별실판매" enable row level security;
alter table public."YES24구매자스냅샷" enable row level security;
alter table public."YES24구매자분포" enable row level security;
alter table public."YES24구매자스테이징" enable row level security;

revoke all on table public."SCM거래처" from anon, authenticated;
revoke all on table public."SCM제품매핑" from anon, authenticated;
revoke all on table public."SCM동기화이력" from anon, authenticated;
revoke all on table public."SCM동기화스테이징" from anon, authenticated;
revoke all on table public."SCM동기화거래처결과" from anon, authenticated;
revoke all on table public."SCM일별실판매" from anon, authenticated;
revoke all on table public."YES24구매자스냅샷" from anon, authenticated;
revoke all on table public."YES24구매자분포" from anon, authenticated;
revoke all on table public."YES24구매자스테이징" from anon, authenticated;
revoke all on sequence public."SCM동기화거래처결과_결과ID_seq" from anon, authenticated;
revoke all on sequence public."SCM일별실판매_SCM실판매ID_seq" from anon, authenticated;
revoke all on sequence public."YES24구매자스냅샷_스냅샷ID_seq" from anon, authenticated;

grant select, insert, update, delete on table public."SCM거래처" to service_role;
grant select, insert, update, delete on table public."SCM제품매핑" to service_role;
grant select, insert, update, delete on table public."SCM동기화이력" to service_role;
grant select, insert, update, delete on table public."SCM동기화스테이징" to service_role;
grant select, insert, update, delete on table public."SCM동기화거래처결과" to service_role;
grant select, insert, update, delete on table public."SCM일별실판매" to service_role;
grant select, insert, update, delete on table public."YES24구매자스냅샷" to service_role;
grant select, insert, update, delete on table public."YES24구매자분포" to service_role;
grant select, insert, update, delete on table public."YES24구매자스테이징" to service_role;
grant usage, select on sequence public."SCM동기화거래처결과_결과ID_seq" to service_role;
grant usage, select on sequence public."SCM일별실판매_SCM실판매ID_seq" to service_role;
grant usage, select on sequence public."YES24구매자스냅샷_스냅샷ID_seq" to service_role;
revoke all on function public."SCM동기화확정"(uuid) from public, anon, authenticated;
grant execute on function public."SCM동기화확정"(uuid) to service_role;
